In [2]:
# Data Extraction

import pyreadstat
import pandas as pd

path = r"c:\Users\usher\Downloads\NGIR7BDT\NGIR7BFL.DTA"

df, meta = pyreadstat.read_dta(path)

print("Dataset loaded sucessfully")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Dataset loaded sucessfully
Rows: 41821
Columns: 5394

In [3]:
print("First 30 variables:")
print(df.columns[:30].tolist())

print("\nLast 30 variables:")
print(df.columns[-30:].tolist())

First 30 variables:
['caseid', 'v000', 'v001', 'v002', 'v003', 'v004', 'v005', 'v006', 'v007', 'v008', 'v008a', 'v009', 'v010', 'v011', 'v012', 'v013', 'v014', 'v015', 'v016', 'v017', 'v018', 'v019', 'v019a', 'v020', 'v021', 'v022', 'v023', 'v024', 'v025', 'v026']

Last 30 variables:
['s434ig_1', 's434ig_2', 's434ig_3', 's434ig_4', 's434ig_5', 's434ig_6', 's434ix_1', 's434ix_2', 's434ix_3', 's434ix_4', 's434ix_5', 's434ix_6', 's434iz_1', 's434iz_2', 's434iz_3', 's434iz_4', 's434iz_5', 's434iz_6', 's434k_1', 's434k_2', 's434k_3', 's434k_4', 's434k_5', 's434k_6', 's434l_1', 's434l_2', 's434l_3', 's434l_4', 's434l_5', 's434l_6']

In [4]:
df.head(10)

,caseid,v000,v001,v002,v003,v004,v005,v006,v007,v008,...,s434k_3,s434k_4,s434k_5,s434k_6,s434l_1,s434l_2,s434l_3,s434l_4,s434l_5,s434l_6
0,1 1 2,NG7,1,1,2,1,1335530,9,2018,1425,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1 6 4,NG7,1,6,4,1,1335530,9,2018,1425,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1 11 1,NG7,1,11,1,1,1335530,9,2018,1425,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1 25 2,NG7,1,25,2,1,1335530,9,2018,1425,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1 30 1,NG7,1,30,1,1,1335530,9,2018,1425,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1 35 2,NG7,1,35,2,1,1335530,9,2018,1425,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1 40 3,NG7,1,40,3,1,1335530,9,2018,1425,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1 40 5,NG7,1,40,5,1,1335530,9,2018,1425,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1 45 2,NG7,1,45,2,1,1335530,9,2018,1425,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1 54 1,NG7,1,54,1,1,1335530,9,2018,1425,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
print(df['v024'].value_counts().sort_index())
print(meta.variable_value_labels.get("v024"))

v024
1     7772
2     7639
3    10129
4     5571
5     5080
6     5630
Name: count, dtype: int64
{1: 'north central', 2: 'north east', 3: 'north west', 4: 'south east', 5: 'south south', 6: 'south west'}

In [6]:
# finding the possible maternal-health variables

keywords = [
    "birth",
    "pregnancy",
    "maternal",
    "antenatal",
    "delivery",
    "health",
    "faculty",
    "skilled",
    "contraceptive"
]

label_matches = []

for col, label in meta.column_names_to_labels.items():
    label_text = str(label).lower()

    if any(keyword in label_text for keyword in keywords):
        label_matches.append((col, label))

print("Number of matching variables:", len(label_matches))

for col, label in label_matches:
    print(f"{col} - {label}")

Number of matching variables: 1283
v009 - respondent's month of birth
v010 - respondent's year of birth
v011 - date of birth (cmc)
bidx_01 - birth column number
bidx_02 - birth column number
bidx_03 - birth column number
bidx_04 - birth column number
bidx_05 - birth column number
bidx_06 - birth column number
bidx_07 - birth column number
bidx_08 - birth column number
bidx_09 - birth column number
bidx_10 - birth column number
bidx_11 - birth column number
bidx_12 - birth column number
bidx_13 - birth column number
bidx_14 - birth column number
bidx_15 - birth column number
bidx_16 - birth column number
bidx_17 - birth column number
bidx_18 - birth column number
bidx_19 - birth column number
bidx_20 - birth column number
bord_01 - birth order number
bord_02 - birth order number
bord_03 - birth order number
bord_04 - birth order number
bord_05 - birth order number
bord_06 - birth order number
bord_07 - birth order number
bord_08 - birth order number
bord_09 - birth order number
bord_10 - birth order number
bord_11 - birth order number
bord_12 - birth order number
bord_13 - birth order number
bord_14 - birth order number
bord_15 - birth order number
bord_16 - birth order number
bord_17 - birth order number
bord_18 - birth order number
bord_19 - birth order number
bord_20 - birth order number
b1_01 - month of birth
b1_02 - month of birth
b1_03 - month of birth
b1_04 - month of birth
b1_05 - month of birth
b1_06 - month of birth
b1_07 - month of birth
b1_08 - month of birth
b1_09 - month of birth
b1_10 - month of birth
b1_11 - month of birth
b1_12 - month of birth
b1_13 - month of birth
b1_14 - month of birth
b1_15 - month of birth
b1_16 - month of birth
b1_17 - month of birth
b1_18 - month of birth
b1_19 - month of birth
b1_20 - month of birth
b2_01 - year of birth
b2_02 - year of birth
b2_03 - year of birth
b2_04 - year of birth
b2_05 - year of birth
b2_06 - year of birth
b2_07 - year of birth
b2_08 - year of birth
b2_09 - year of birth
b2_10 - year of birth
b2_11 - year of birth
b2_12 - year of birth
b2_13 - year of birth
b2_14 - year of birth
b2_15 - year of birth
b2_16 - year of birth
b2_17 - year of birth
b2_18 - year of birth
b2_19 - year of birth
b2_20 - year of birth
b3_01 - date of birth (cmc)
b3_02 - date of birth (cmc)
b3_03 - date of birth (cmc)
b3_04 - date of birth (cmc)
b3_05 - date of birth (cmc)
b3_06 - date of birth (cmc)
b3_07 - date of birth (cmc)
b3_08 - date of birth (cmc)
b3_09 - date of birth (cmc)
b3_10 - date of birth (cmc)
b3_11 - date of birth (cmc)
b3_12 - date of birth (cmc)
b3_13 - date of birth (cmc)
b3_14 - date of birth (cmc)
b3_15 - date of birth (cmc)
b3_16 - date of birth (cmc)
b3_17 - date of birth (cmc)
b3_18 - date of birth (cmc)
b3_19 - date of birth (cmc)
b3_20 - date of birth (cmc)
b11_01 - preceding birth interval (months)
b11_02 - preceding birth interval (months)
b11_03 - preceding birth interval (months)
b11_04 - preceding birth interval (months)
b11_05 - preceding birth interval (months)
b11_06 - preceding birth interval (months)
b11_07 - preceding birth interval (months)
b11_08 - preceding birth interval (months)
b11_09 - preceding birth interval (months)
b11_10 - preceding birth interval (months)
b11_11 - preceding birth interval (months)
b11_12 - preceding birth interval (months)
b11_13 - preceding birth interval (months)
b11_14 - preceding birth interval (months)
b11_15 - preceding birth interval (months)
b11_16 - preceding birth interval (months)
b11_17 - preceding birth interval (months)
b11_18 - preceding birth interval (months)
b11_19 - preceding birth interval (months)
b11_20 - preceding birth interval (months)
b12_01 - succeeding birth interval (months)
b12_02 - succeeding birth interval (months)
b12_03 - succeeding birth interval (months)
b12_04 - succeeding birth interval (months)
b12_05 - succeeding birth interval (months)
b12_06 - succeeding birth interval (months)
b12_07 - succeeding birth interval (months)
b12_08 - succeeding birth interval (months)
b12_09 - succeeding birth interval (months)
b12_10 - succeeding birth interval (months)
b12_11 - succeeding birth interval (months)
b12_12 - succeeding birth interval (months)
b12_13 - succeeding birth interval (months)
b12_14 - succeeding birth interval (months)
b12_15 - succeeding birth interval (months)
b12_16 - succeeding birth interval (months)
b12_17 - succeeding birth interval (months)
b12_18 - succeeding birth interval (months)
b12_19 - succeeding birth interval (months)
b12_20 - succeeding birth interval (months)
b15_01 - live birth between births
b15_02 - live birth between births
b15_03 - live birth between births
b15_04 - live birth between births
b15_05 - live birth between births
b15_06 - live birth between births
b15_07 - live birth between births
b15_08 - live birth between births
b15_09 - live birth between births
b15_10 - live birth between births
b15_11 - live birth between births
b15_12 - live birth between births
b15_13 - live birth between births
b15_14 - live birth between births
b15_15 - live birth between births
b15_16 - live birth between births
b15_17 - live birth between births
b15_18 - live birth between births
b15_19 - live birth between births
b15_20 - live birth between births
b17_01 - day of birth
b17_02 - day of birth
b17_03 - day of birth
b17_04 - day of birth
b17_05 - day of birth
b17_06 - day of birth
b17_07 - day of birth
b17_08 - day of birth
b17_09 - day of birth
b17_10 - day of birth
b17_11 - day of birth
b17_12 - day of birth
b17_13 - day of birth
b17_14 - day of birth
b17_15 - day of birth
b17_16 - day of birth
b17_17 - day of birth
b17_18 - day of birth
b17_19 - day of birth
b17_20 - day of birth
b18_01 - century day code of birth (cdc)
b18_02 - century day code of birth (cdc)
b18_03 - century day code of birth (cdc)
b18_04 - century day code of birth (cdc)
b18_05 - century day code of birth (cdc)
b18_06 - century day code of birth (cdc)
b18_07 - century day code of birth (cdc)
b18_08 - century day code of birth (cdc)
b18_09 - century day code of birth (cdc)
b18_10 - century day code of birth (cdc)
b18_11 - century day code of birth (cdc)
b18_12 - century day code of birth (cdc)
b18_13 - century day code of birth (cdc)
b18_14 - century day code of birth (cdc)
b18_15 - century day code of birth (cdc)
b18_16 - century day code of birth (cdc)
b18_17 - century day code of birth (cdc)
b18_18 - century day code of birth (cdc)
b18_19 - century day code of birth (cdc)
b18_20 - century day code of birth (cdc)
b19_01 - current age of child in months (months since birth for dead children)
b19_02 - current age of child in months (months since birth for dead children)
b19_03 - current age of child in months (months since birth for dead children)
b19_04 - current age of child in months (months since birth for dead children)
b19_05 - current age of child in months (months since birth for dead children)
b19_06 - current age of child in months (months since birth for dead children)
b19_07 - current age of child in months (months since birth for dead children)
b19_08 - current age of child in months (months since birth for dead children)
b19_09 - current age of child in months (months since birth for dead children)
b19_10 - current age of child in months (months since birth for dead children)
b19_11 - current age of child in months (months since birth for dead children)
b19_12 - current age of child in months (months since birth for dead children)
b19_13 - current age of child in months (months since birth for dead children)
b19_14 - current age of child in months (months since birth for dead children)
b19_15 - current age of child in months (months since birth for dead children)
b19_16 - current age of child in months (months since birth for dead children)
b19_17 - current age of child in months (months since birth for dead children)
b19_18 - current age of child in months (months since birth for dead children)
b19_19 - current age of child in months (months since birth for dead children)
b19_20 - current age of child in months (months since birth for dead children)
b20_01 - duration of pregnancy
b20_02 - duration of pregnancy
b20_03 - duration of pregnancy
b20_04 - duration of pregnancy
b20_05 - duration of pregnancy
b20_06 - duration of pregnancy
b20_07 - duration of pregnancy
b20_08 - duration of pregnancy
b20_09 - duration of pregnancy
b20_10 - duration of pregnancy
b20_11 - duration of pregnancy
b20_12 - duration of pregnancy
b20_13 - duration of pregnancy
b20_14 - duration of pregnancy
b20_15 - duration of pregnancy
b20_16 - duration of pregnancy
b20_17 - duration of pregnancy
b20_18 - duration of pregnancy
b20_19 - duration of pregnancy
b20_20 - duration of pregnancy
v208 - births in last five years
v209 - births in past year
v210 - births in month of interview
v211 - date of first birth (cmc)
v212 - age of respondent at 1st birth
v214 - duration of current pregnancy
v219 - living children + current pregnancy
v220 - living children + current pregnancy (grouped)
v221 - marriage to first birth interval (months)
v222 - last birth to interview (months)
v223 - completeness of current pregnancy information
v224 - entries in birth history
v225 - current pregnancy wanted
v228 - ever had a terminated pregnancy
v229 - month pregnancy ended
v230 - year pregnancy ended
v231 - cmc pregnancy ended
v233 - months when pregnancy ended
v235 - index last child prior to maternity-health (calendar)
v237 - birth between last and interview
v238 - births in last three years
v244 - can women get pregnant after birth and before period
v312 - current contraceptive method
v364 - contraceptive use and intention
v394 - visited health facility last 12 months
v395 - at health facility, told of family planning
v3a00b - na - source of family planning for non-users: government health center
v3a03 - told about side effects by health or family planning worker
v3a06 - told about other family planning methods by health or family planning worker
v3a08o - na - reason not using: health concerns
v3a08p - reason not using: fear of side effects/health concerns
midx_1 - index to birth history
midx_2 - index to birth history
midx_3 - index to birth history
midx_4 - index to birth history
midx_5 - index to birth history
midx_6 - index to birth history
m1_1 - number of tetanus injections before birth
m1_2 - number of tetanus injections before birth
m1_3 - number of tetanus injections before birth
m1_4 - number of tetanus injections before birth
m1_5 - number of tetanus injections before birth
m1_6 - number of tetanus injections before birth
m1a_1 - number of tetanus injections before pregnancy
m1a_2 - number of tetanus injections before pregnancy
m1a_3 - number of tetanus injections before pregnancy
m1a_4 - number of tetanus injections before pregnancy
m1a_5 - number of tetanus injections before pregnancy
m1a_6 - number of tetanus injections before pregnancy
m1b_1 - na - month of last tetanus injection before pregnancy
m1b_2 - na - month of last tetanus injection before pregnancy
m1b_3 - na - month of last tetanus injection before pregnancy
m1b_4 - na - month of last tetanus injection before pregnancy
m1b_5 - na - month of last tetanus injection before pregnancy
m1b_6 - na - month of last tetanus injection before pregnancy
m1c_1 - na - year of last tetanus injection before pregnancy
m1c_2 - na - year of last tetanus injection before pregnancy
m1c_3 - na - year of last tetanus injection before pregnancy
m1c_4 - na - year of last tetanus injection before pregnancy
m1c_5 - na - year of last tetanus injection before pregnancy
m1c_6 - na - year of last tetanus injection before pregnancy
m1d_1 - years ago received last tetanus injection before pregnancy
m1d_2 - years ago received last tetanus injection before pregnancy
m1d_3 - years ago received last tetanus injection before pregnancy
m1d_4 - years ago received last tetanus injection before pregnancy
m1d_5 - years ago received last tetanus injection before pregnancy
m1d_6 - years ago received last tetanus injection before pregnancy
m1e_1 - na - last tetanus injection before pregnancy (cmc)
m1e_2 - na - last tetanus injection before pregnancy (cmc)
m1e_3 - na - last tetanus injection before pregnancy (cmc)
m1e_4 - na - last tetanus injection before pregnancy (cmc)
m1e_5 - na - last tetanus injection before pregnancy (cmc)
m1e_6 - na - last tetanus injection before pregnancy (cmc)
m2d_1 - prenatal: community extension health worker
m2d_2 - prenatal: community extension health worker
m2d_3 - prenatal: community extension health worker
m2d_4 - prenatal: community extension health worker
m2d_5 - prenatal: community extension health worker
m2d_6 - prenatal: community extension health worker
m2e_1 - na - prenatal: cs health professional
m2e_2 - na - prenatal: cs health professional
m2e_3 - na - prenatal: cs health professional
m2e_4 - na - prenatal: cs health professional
m2e_5 - na - prenatal: cs health professional
m2e_6 - na - prenatal: cs health professional
m2f_1 - na - prenatal: cs health professional
m2f_2 - na - prenatal: cs health professional
m2f_3 - na - prenatal: cs health professional
m2f_4 - na - prenatal: cs health professional
m2f_5 - na - prenatal: cs health professional
m2f_6 - na - prenatal: cs health professional
m2g_1 - prenatal: traditional birth attendant
m2g_2 - prenatal: traditional birth attendant
m2g_3 - prenatal: traditional birth attendant
m2g_4 - prenatal: traditional birth attendant
m2g_5 - prenatal: traditional birth attendant
m2g_6 - prenatal: traditional birth attendant
m2h_1 - prenatal: community/village health worker
m2h_2 - prenatal: community/village health worker
m2h_3 - prenatal: community/village health worker
m2h_4 - prenatal: community/village health worker
m2h_5 - prenatal: community/village health worker
m2h_6 - prenatal: community/village health worker
m3d_1 - assistance: community health extension worker
m3d_2 - assistance: community health extension worker
m3d_3 - assistance: community health extension worker
m3d_4 - assistance: community health extension worker
m3d_5 - assistance: community health extension worker
m3d_6 - assistance: community health extension worker
m3e_1 - na - assistance: cs health professional
m3e_2 - na - assistance: cs health professional
m3e_3 - na - assistance: cs health professional
m3e_4 - na - assistance: cs health professional
m3e_5 - na - assistance: cs health professional
m3e_6 - na - assistance: cs health professional
m3f_1 - na - assistance: cs health professional
m3f_2 - na - assistance: cs health professional
m3f_3 - na - assistance: cs health professional
m3f_4 - na - assistance: cs health professional
m3f_5 - na - assistance: cs health professional
m3f_6 - na - assistance: cs health professional
m3g_1 - assistance: traditional birth attendant
m3g_2 - assistance: traditional birth attendant
m3g_3 - assistance: traditional birth attendant
m3g_4 - assistance: traditional birth attendant
m3g_5 - assistance: traditional birth attendant
m3g_6 - assistance: traditional birth attendant
m10_1 - wanted pregnancy when became pregnant
m10_2 - wanted pregnancy when became pregnant
m10_3 - wanted pregnancy when became pregnant
m10_4 - wanted pregnancy when became pregnant
m10_5 - wanted pregnancy when became pregnant
m10_6 - wanted pregnancy when became pregnant
m13_1 - timing of 1st antenatal check (months)
m13_2 - timing of 1st antenatal check (months)
m13_3 - timing of 1st antenatal check (months)
m13_4 - timing of 1st antenatal check (months)
m13_5 - timing of 1st antenatal check (months)
m13_6 - timing of 1st antenatal check (months)
m14_1 - number of antenatal visits during pregnancy
m14_2 - number of antenatal visits during pregnancy
m14_3 - number of antenatal visits during pregnancy
m14_4 - number of antenatal visits during pregnancy
m14_5 - number of antenatal visits during pregnancy
m14_6 - number of antenatal visits during pregnancy
m15_1 - place of delivery
m15_2 - place of delivery
m15_3 - place of delivery
m15_4 - place of delivery
m15_5 - place of delivery
m15_6 - place of delivery
m17_1 - delivery by caesarean section
m17_2 - delivery by caesarean section
m17_3 - delivery by caesarean section
m17_4 - delivery by caesarean section
m17_5 - delivery by caesarean section
m17_6 - delivery by caesarean section
m18_1 - size of child at birth
m18_2 - size of child at birth
m18_3 - size of child at birth
m18_4 - size of child at birth
m18_5 - size of child at birth
m18_6 - size of child at birth
m19_1 - birth weight in kilograms (3 decimals)
m19_2 - birth weight in kilograms (3 decimals)
m19_3 - birth weight in kilograms (3 decimals)
m19_4 - birth weight in kilograms (3 decimals)
m19_5 - birth weight in kilograms (3 decimals)
m19_6 - birth weight in kilograms (3 decimals)
m19a_1 - weight at birth/recall
m19a_2 - weight at birth/recall
m19a_3 - weight at birth/recall
m19a_4 - weight at birth/recall
m19a_5 - weight at birth/recall
m19a_6 - weight at birth/recall
m42a_1 - na - during pregnancy: weighed
m42a_2 - na - during pregnancy: weighed
m42a_3 - na - during pregnancy: weighed
m42a_4 - na - during pregnancy: weighed
m42a_5 - na - during pregnancy: weighed
m42a_6 - na - during pregnancy: weighed
m42b_1 - na - during pregnancy: height measured
m42b_2 - na - during pregnancy: height measured
m42b_3 - na - during pregnancy: height measured
m42b_4 - na - during pregnancy: height measured
m42b_5 - na - during pregnancy: height measured
m42b_6 - na - during pregnancy: height measured
m42c_1 - during pregnancy: blood pressure taken
m42c_2 - during pregnancy: blood pressure taken
m42c_3 - during pregnancy: blood pressure taken
m42c_4 - during pregnancy: blood pressure taken
m42c_5 - during pregnancy: blood pressure taken
m42c_6 - during pregnancy: blood pressure taken
m42d_1 - during pregnancy: urine sample taken
m42d_2 - during pregnancy: urine sample taken
m42d_3 - during pregnancy: urine sample taken
m42d_4 - during pregnancy: urine sample taken
m42d_5 - during pregnancy: urine sample taken
m42d_6 - during pregnancy: urine sample taken
m42e_1 - during pregnancy: blood sample taken
m42e_2 - during pregnancy: blood sample taken
m42e_3 - during pregnancy: blood sample taken
m42e_4 - during pregnancy: blood sample taken
m42e_5 - during pregnancy: blood sample taken
m42e_6 - during pregnancy: blood sample taken
m43_1 - na - told about pregnancy complications
m43_2 - na - told about pregnancy complications
m43_3 - na - told about pregnancy complications
m43_4 - na - told about pregnancy complications
m43_5 - na - told about pregnancy complications
m43_6 - na - told about pregnancy complications
m44_1 - na - told where to go for pregnancy complications
m44_2 - na - told where to go for pregnancy complications
m44_3 - na - told where to go for pregnancy complications
m44_4 - na - told where to go for pregnancy complications
m44_5 - na - told where to go for pregnancy complications
m44_6 - na - told where to go for pregnancy complications
m45_1 - during pregnancy, given or bought iron tablets/syrup
m45_2 - during pregnancy, given or bought iron tablets/syrup
m45_3 - during pregnancy, given or bought iron tablets/syrup
m45_4 - during pregnancy, given or bought iron tablets/syrup
m45_5 - during pregnancy, given or bought iron tablets/syrup
m45_6 - during pregnancy, given or bought iron tablets/syrup
m47_1 - na - during pregnancy, had difficulty with daylight vision
m47_2 - na - during pregnancy, had difficulty with daylight vision
m47_3 - na - during pregnancy, had difficulty with daylight vision
m47_4 - na - during pregnancy, had difficulty with daylight vision
m47_5 - na - during pregnancy, had difficulty with daylight vision
m47_6 - na - during pregnancy, had difficulty with daylight vision
m48_1 - na - during pregnancy, had difficulty with night blindness
m48_2 - na - during pregnancy, had difficulty with night blindness
m48_3 - na - during pregnancy, had difficulty with night blindness
m48_4 - na - during pregnancy, had difficulty with night blindness
m48_5 - na - during pregnancy, had difficulty with night blindness

In [7]:
# Identifying the exact variables available

candidate_vars = [
    "v024",  # Region
    "v025",  # Urban/rural
    "v012",  # Age
    "v106",  # Education
    "v190",  # Wealth index
    "v714",  # currently working
    "v130",  # Ethnicity
    "v131",  # Religion
    "v151",  # Sex of household head
    "v481",  # Health insurance
]

for var in candidate_vars:
    if var in df.columns:
        print(f"{var} - {meta.column_names_to_labels.get(var)}")
    else:
        print(f"{var} - NOT FOUND")

v024 - region
v025 - type of place of residence
v012 - respondent's current age
v106 - highest educational level
v190 - wealth index combined
v714 - respondent currently working
v130 - religion
v131 - ethnicity
v151 - sex of household head
v481 - covered by health insurance

In [8]:
df[candidate_vars].head()

   v024  v025  v012  v106  v190  v714  v130  v131  v151  v481
0     1     1    40     3     5     1     2     6     1     0
1     1     1    16     2     5     0     2     9     1     0
2     1     1    37     3     5     0     1     9     2     0
3     1     1    27     3     5     1     2    96     1     0
4     1     1    29     2     5     1     2    96     2     0

In [9]:
# checking the quallity of the variables

candidate_vars = [
    "v024", "v025", "v012", "v106", 'v190',
    "v714", "v130", "v131", "v151", "v481"
]

missing = df[candidate_vars].isna().sum()

print("Missing values:", missing)

print("\nMissing percentage:")
print((missing / len(df) * 100).round(2))

Missing values: v024    0
v025    0
v012    0
v106    0
v190    0
v714    0
v130    0
v131    0
v151    0
v481    0
dtype: int64

Missing percentage:
v024    0.0
v025    0.0
v012    0.0
v106    0.0
v190    0.0
v714    0.0
v130    0.0
v131    0.0
v151    0.0
v481    0.0
dtype: float64

In [10]:
# Understanding the value labels for these variables

for var in candidate_vars:
    print(f"\n{'='*50}")
    print(f"{var} - {meta.column_names_to_labels.get(var)}")
    print(meta.variable_value_labels.get(var, "No value labels"))

==================================================
v024 - region
{1: 'north central', 2: 'north east', 3: 'north west', 4: 'south east', 5: 'south south', 6: 'south west'}

==================================================
v025 - type of place of residence
{1: 'urban', 2: 'rural'}

==================================================
v012 - respondent's current age
No value labels

==================================================
v106 - highest educational level
{0: 'no education', 1: 'primary', 2: 'secondary', 3: 'higher'}

==================================================
v190 - wealth index combined
{1: 'poorest', 2: 'poorer', 3: 'middle', 4: 'richer', 5: 'richest'}

==================================================
v714 - respondent currently working
{0: 'no', 1: 'yes'}

==================================================
v130 - religion
{1: 'catholic', 2: 'other christian', 3: 'islam', 4: 'traditionalist', 96: 'other'}

==================================================
v131 - ethnicity
{1: 'ekoi', 2: 'fulani', 3: 'hausa', 4: 'ibibio', 5: 'igala', 6: 'igbo', 7: 'ijaw/izon', 8: 'kanuri/beriberi', 9: 'tiv', 10: 'yoruba', 96: 'other', 98: "don't know"}

==================================================
v151 - sex of household head
{1: 'male', 2: 'female'}

==================================================
v481 - covered by health insurance
{0: 'no', 1: 'yes'}

In [11]:
# investigating the actual maternal-health outcomes

outcome_candidates = [
    "m15_1",  # Place of delivery
    "m14_1",  # number of antenatal visits
    "m13_1",  # timing of first antenatal visit
    "m17_1",  # Caesarean section
]

for var in outcome_candidates:
    print("\n" + "="*50)
    print(f"{var} - {meta.column_names_to_labels.get(var)}")
    print("Values Labels:")
    print(meta.variable_value_labels.get(var, "No value labels"))

    print("\nValue counts:")
    print(df[var].value_counts(dropna=False).sort_index())

==================================================
m15_1 - place of delivery
Values Labels:
{10: 'home', 11: "respondent's home", 12: 'other home', 20: 'public sector', 21: 'government hospital', 22: 'government health center', 23: 'government health post', 26: 'other public sector', 30: 'private sector', 31: 'private hospital/clinic', 36: 'other private sector', 96: 'other'}

Value counts:
m15_1
11     11267
12      1174
21      2972
22      3081
23       243
26        13
31      2647
36        45
96       350
NaN    20029
Name: count, dtype: int64

==================================================
m14_1 - number of antenatal visits during pregnancy
Values Labels:
{0: 'no antenatal visits', 98: "don't know"}

Value counts:
m14_1
0       5365
1        583
2        968
3       2242
4       2716
5       2344
6       2095
7       1055
8       1079
9        443
10       806
11       160
12       472
13        80
14       113
15       231
16       166
17        56
18       115
19        33
20       343
98       327
NaN    20029
Name: count, dtype: int64

==================================================
m13_1 - timing of 1st antenatal check (months)
Values Labels:
{98: "don't know"}

Value counts:
m13_1
0         11
1        332
2        895
3       2788
4       4226
5       3672
6       2453
7       1581
8        343
9         95
10         2
98        29
NaN    25394
Name: count, dtype: int64

==================================================
m17_1 - delivery by caesarean section
Values Labels:
{0: 'no', 1: 'yes'}

Value counts:
m17_1
0      21055
1        647
NaN    20119
Name: count, dtype: int64

In [12]:
## Creating a temporary binary version of m15_1 (place of delivery)
# Create a temporary binary facility-delivery outcome
# 0 = home delivery
# 1 = facility delivery

facility_delivery = df["m15_1"].map(
    lambda x: 0 if x in [10, 11, 12]
    else 1 if x in [20, 21, 22, 23, 24, 26, 30, 31, 36]
    else None
)

print("Overall outcome distribution:")
print(facility_delivery.value_counts(dropna=False))

Overall outcome distribution:
m15_1
NaN    20379
0.0    12441
1.0     9001
Name: count, dtype: int64

In [13]:
print("\nFacility delivery by region:")

regional_table = pd.crosstab(
    df["v024"],
    facility_delivery,
    normalize="index"
) * 100

regional_table.index = [
    "North Central",
    "North East",
    "North West",
    "South East",
    "South South",
    "South West"
]

regional_table.columns = ["Home//Non-Facility (%)", "Facility (%)"]

print(regional_table.round(2))

Facility delivery by region:
               Home//Non-Facility (%)  Facility (%)
North Central                   47.97         52.03
North East                      74.01         25.99
North West                      84.32         15.68
South East                      19.29         80.71
South South                     51.32         48.68
South West                      18.66         81.34

In [14]:
df = df.dropna(subset=["m15_1"])

In [15]:
print("Births in last 5 years:")
print(df["v208"].value_counts(dropna=False).sort_index())

Births in last 5 years:
v208
1    11363
2     8852
3     1461
4      108
5        6
6        2
Name: count, dtype: int64

In [16]:
print("m15_1 by v208:")
print(
    pd.crosstab(
        df["v208"],
        df["m15_1"],
        dropna=False
    )
)

m15_1 by v208:
m15_1    11   12    21    22   23  26    31  36   96
v208
1      5255  679  1775  1751  142   7  1524  22  208
2      5145  413  1022  1118   82   6   923  19  124
3       806   76   160   198   17   0   183   4   17
4        58    5    12    13    2   0    17   0    1
5         3    1     2     0    0   0     0   0    0
6         0    0     1     1    0   0     0   0    0

In [17]:
## Feature Selection

feature_candidates = [
    "v012",   # Age
    "v025",   # Urban/rural
    "v106",   # Education
    "v190",   # Wealth index
    "v714",   # Currently working
    "v151",   # Sex of household head
    "v481",   # Health insurance
    "v208"    # Number of births in last 5 years
]

for var in feature_candidates:
    print("\n" + "=" * 60)
    print(f"{var} → {meta.column_names_to_labels.get(var)}")
    
    print("\nValue counts:")
    print(df[var].value_counts(dropna=False).sort_index())

============================================================
v012 → respondent's current age

Value counts:
v012
15      17
16      69
17     245
18     453
19     409
20    1163
21     586
22     931
23     807
24     719
25    1868
26     911
27     995
28    1099
29     744
30    1817
31     645
32     906
33     698
34     604
35    1405
36     613
37     533
38     671
39     400
40     799
41     287
42     337
43     216
44     135
45     349
46     114
47     100
48      96
49      51
Name: count, dtype: int64

============================================================
v025 → type of place of residence

Value counts:
v025
1     7710
2    14082
Name: count, dtype: int64

============================================================
v106 → highest educational level

Value counts:
v106
0    9527
1    3410
2    7064
3    1791
Name: count, dtype: int64

============================================================
v190 → wealth index combined

Value counts:
v190
1    5025
2    4905
3    4586
4    4025
5    3251
Name: count, dtype: int64

============================================================
v714 → respondent currently working

Value counts:
v714
0     6977
1    14815
Name: count, dtype: int64

============================================================
v151 → sex of household head

Value counts:
v151
1    19512
2     2280
Name: count, dtype: int64

============================================================
v481 → covered by health insurance

Value counts:
v481
0    21298
1      494
Name: count, dtype: int64

============================================================
v208 → births in last five years

Value counts:
v208
1    11363
2     8852
3     1461
4      108
5        6
6        2
Name: count, dtype: int64

In [ ]:
# First Baseline feature set

baseline_features = [
    "v012",  # Age
    "v025",  # Urban/rural residence
    "v016",  # Education
    "v190",  # Wealth index
    "v714",  # Currently working
]

client_variable = "v024"

target_variable = "m15_1"

In [19]:
# Creating a temporary modelling subset

temp_df = df[df["m15_1"].notna()].copy()

print("Total eligible observations:", len(temp_df))

print("\nObservations per region:")
print(temp_df["v024"].value_counts().sort_index())

print("\nHome vs Facility delivery per region:")

print(
    pd.crosstab(
        temp_df["v024"],
        facility_delivery[temp_df.index]
    )
)

Total eligible observations: 21792

Observations per region:
v024
1    3875
2    4506
3    6309
4    2365
5    2174
6    2563
Name: count, dtype: int64

Home vs Facility delivery per region:
m15_1   0.0   1.0
v024
1      1841  1997
2      3329  1169
3      5318   989
4       451  1887
5      1052   998
6       450  1961

In [20]:
# Checking whether code 96 explains the discrepancy

print("Records with m15_1 = 96 by region:\n")

print(
    temp_df[temp_df["m15_1"] == 96]
    .groupby("v024")
    .size()
)

print("\nTotal records coded as 96:")
print((temp_df["m15_1"] == 96).sum())

Records with m15_1 = 96 by region:

v024
1     37
2      8
3      2
4     27
5    124
6    152
dtype: int64

Total records coded as 96:
350

In [23]:
# Creating a clean binary facility-delivery target

home_codes = [11, 12]

facility_codes = [21, 22, 23, 26, 31, 36]

# Starting with the eligible population
model_df = df[df["m15_1"].notna()].copy()

# Creating the binary target
model_df["facility_delivery"] = model_df["m15_1"].map(
    lambda x: 0 if x in home_codes
    else 1 if x in facility_codes
    else None
)

# removing observations that cannot be clearly classified
model_df = model_df.dropna(subset=["facility_delivery"]).copy()

# Converting target to integer
model_df["facility_delivery"] = model_df["facility_delivery"].astype(int)

print("Final modelling observations:", len(model_df))

print("\nTarget distribution:")
print(model_df["facility_delivery"].value_counts())

print("\nTarget Percentage:")
print(
    model_df["facility_delivery"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

Final modelling observations: 21442

Target distribution:
facility_delivery
0    12441
1     9001
Name: count, dtype: int64

Target Percentage:
facility_delivery
0    58.02
1    41.98
Name: proportion, dtype: float64

In [ ]:
# Validating the final dataset across our  six clients

# Number of observation per federated client

print("Observations per region:")
print(model_df["v024"].value_counts().sort_index())


# Home vs Facility delivery by region

print("\nHome vs Facility delivery by region:")

regional_distribution = pd.crosstab(
    model_df["v024"],
    model_df["facility_delivery"]
)

print(regional_distribution)


# Percentage distribution of region

print("\nPercentage distribution by region:")

regional_percentage = (
    pd.crosstab(
        model_df["v024"],
        model_df["facility_delivery"],
        normalize="index"
    )
    * 100
).round(2)

print(regional_percentage)

Observations per region:
v024
1    3838
2    4498
3    6307
4    2338
5    2050
6    2411
Name: count, dtype: int64

Home vs Facility delivery by region:
facility_delivery     0     1
v024
1                  1841  1997
2                  3329  1169
3                  5318   989
4                   451  1887
5                  1052   998
6                   450  1961

Percentage distribution by region:
facility_delivery      0      1
v024
1                  47.97  52.03
2                  74.01  25.99
3                  84.32  15.68
4                  19.29  80.71
5                  51.32  48.68
6                  18.66  81.34